name: Fetch Arxiv Papers

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch_arxiv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 选择你需要的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arxiv pyyaml requests

      - name: Run fetch_arxiv script
        run: python fetch_arxiv.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update arXiv data"
          files: arxiv_data.json
          rebase: 'true'
          name: github-actions
          email: github-actions@github.com
